name: Build & Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_run:
    workflows: ["release"]
    types: [completed]

# Required for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure we always get the latest main branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs & plugins
        working-directory: docs
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install mkdocs mkdocs-material; fi

      # Build the site *without* committing it anywhere
      - name: Build MkDocs site
        run: |
          cd docs
          mkdocs build --site-dir ../site --verbose
          cd ..
          echo "Build completed. Site contents:"
          ls -la site/
          touch site/.nojekyll
          echo ".nojekyll file created"
          
          # Copy APT repository to the site for GitHub Pages
          echo "Copying APT repository to site..."
          cp -r apt-repo site/
          echo "APT repository copied"

      # Package the static files as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site   # must match the --site-dir above

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
